### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by coridone** [Slattz/ACNL_REditor#3]
Would it be possible to implement a way to have multiple save slots in the game, with each slot being used for different mayors and different cities?

**Comment by Slattz** [comment]
Theoretically, yes, but realistically, probably not. It'd likely be way too much work to try implement. The way I could see it done is pressing a specific button while the game is starting up which then selects a save slot. It'd be much harder for there to be an actual menu selection option. Also, save files would need to be renamed internally, so instead of having just the `garden_plus.dat`, you'd have a `garden_plus0.dat`, `garden_plus1.dat`, etc. A big rework would be needed to how the game operates when reading the save and also saving too.

I'm gonna leave this open, as it is something that I may take a look at when I have alot of time, and it'd be interesting to work on. Perhaps someone else may also want to try it.

**Comment by dvdcd** [comment]
[Just use town manager](https://gbatemp.net/threads/townmanager-an-ac-nl-town-management-tool.458212/)

**Comment by Slattz** [comment]
Update: I've decided I'm not going to add this, as said above, it's not that necessary really when apps that do it already exist.
